### PR TITLE
First commit of the parser.

### PR DESCRIPTION
**Pull request by denis-bogdanas**
Parsing ERC20 example up to 4th statement.

### CODE REVIEW

**Comment by fubuloubu** [comment]
Um, definitely needs a description. Why is this necessary?

**Comment by fubuloubu** [comment]
Was this generated?

**Comment by denis-bogdanas** [comment]
What do you mean? I'm a recent collaborator on the semantics. Cannot commit directly, so I created a fork and a pull request from there.

**Comment by fubuloubu** [comment]
Oh, I meant did this come out of the k framework or did you create this to help with the k framework in some way? Just trying to figure out if this someway duplicates what we're doing in the compiler itself, or if we could make use of it in some way

**Comment by daejunpark** [comment]
@fubuloubu Currently, KViper requires a Viper program to be given in an [abstract syntax tree format](https://github.com/kframework/viper-semantics/blob/master/common/viper-abstract-syntax.k), since we haven't specified the concrete syntax of Viper.

In the meantime, we need a front-end parser that enables KViper to take a plain Viper program as it is. The front-end parser hooks the production Viper parser to emit an AST in a text format that the current KViper can parse back.

**Comment by fubuloubu** [comment]
@daejunpark Gotcha. I realized after writing (then deleting) my first comment that this PR wasn't actually on the viper repo lol

**Pull request merged**
